# Generated by Django 4.2.16 on 2024-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
