# Generated by Django 4.2.16 on 2024-12-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_likedislike_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video'),
        ),
    ]
